Clase 4
=======

Objetivos:

1. Simulación de flujos metabólicos usando programación lineal
2. Implementación de problemas de programación lineal con numpy y scipy

Simulación de flujos metabólicos usando Programación lineal
===========

La distribución de flujos metabolicos de una celula puede ser modelado como:

\begin{align}
\mbox{max}\ & f(x)=c^Tx \\
\mbox{s.a.} & \\
&Sx=0 \\
&LB<=x<=UB
\end{align}

En donde `S` es la matriz estequiométrica, `x` los flujos metabólicos, y `LB` y `UB` que son los limites inferiores (lower bound) y superiores (upper bound) de cada flujo. Por otra parte, `c` contiene los coeficientes que ponderan el aporte de cada `x` a la generación de una función apropiada, las cuales tipicamente corresponden a biomasa o producción de energía. 

Para resolver este tipo de problemas usando el método simplex existe la librería `scipy.optimize.linprog`. Típicamente un modelo métabolica consiste en restricciones de igualdad, por ejemplo: 


\begin{align}
\mbox{min}\ &f(x)=70x_i+80X_2+85X_3 \\
\mbox{s.a:}\ & \\
&x_1+x_2+x_3+x_4=999 \\
&x_1+4x_2+8x_3+x_5 = 4500 \\
&40x_1 + 30x_2 +20x_3 = 36000 \\
&3x_1 + 2x_2 +4x_3 +x_6= 2700 \\
&x>=0
\end{align}

puede ser resuelto con la siguiente sintaxis:

``` python
import numpy as np
from scipy.optimize import linprog
from numpy.linalg import solve

A = np.array([
[1, 1, 1, 0, 0, 0],
[1, 4, 8, 1, 0, 0],
[40, 30, 20, 0, 1, 0],
[3, 2, 4, 0, 0, 1]])

b = np.array([999, 4500, 36000, 2700])
c = np.array([70, 80, 85, 0, 0, 0])

res = linprog(c, A_eq=A, b_eq=b, bounds=(0, None))
print('Optimal value:', res.fun, '\nX:', res.x)
```
Sin embargo, `linprog` tambien nos permite resolver problemas en donde las restricciones son una mezcla de igualdades y desigualdades. Por ejemplo:

\begin{align}
\mbox{min}\ &f(x)=70x_i+80X_2+85X_3 \\
\mbox{s.a:}\ & \\
&x_1+x_2+x_3=999 \\
&x_1+4x_2+8x_3 \le 4500 \\
&40x_1 + 30x_2 +20x_3 \le 36000 \\
&3x_1 + 2x_2 +4x_3 \le 2700 \\
&x>=0
\end{align}

Puede ser resuelto con las siguiente sintaxis:

``` python
import numpy as np
from scipy.optimize import linprog
from numpy.linalg import solve

A_eq = np.array([[1,1,1]])
b_eq = np.array([999])

A_ub = np.array([
[1, 4, 8],
[40,30,20],
[3,2,4]])

b_ub = np.array([4500, 36000,2700])

c = np.array([70, 80, 85])

res = linprog(c, A_eq=A_eq, b_eq=b_eq, A_ub=A_ub, b_ub=b_ub,
bounds=(0, None))
print('Optimal value:', res.fun, '\nX:', res.x)
```

Ejercicio 1
-----------

1. Escribe una función para resolver simular los flujos de la siguiente red metabólica.
2. Guarda tu función como un script.
3. Ejecuta tu función desde el terminal.

Nota: Usa la estructura de programación que vimos en la clase pasada.

Tarea
===

Para redes metabólicas más grandes es inpractico usar esta formulación. Por suerte existe una libreria `cobrapy` diseñada para facilitar esta tarea la será introducidad durante la próxima clase. Para esto deben traer instalado `cobrapy` en sus computadores, lo cual pueden hacer abriendo el terminal de anaconda y ejecutando el siguiente comando:


```
conda install cobra
```

In [1]:
import numpy as np
from scipy.optimize import linprog
from numpy.linalg import solve

S = np.zeros((6,8))
S[0,0]=1
S[0,5]=-1
S[1,1]=2
S[1,5]=-2
S[1,6]=-2
S[2,5]=1
S[2,6]=-1
S[2,7]=1
S[3,5]=-1
S[3,6]=1
S[3,7]=1
S[3,3]=-1
S[4,2]=-1
S[4,6]=1
S[4,7]=-1
S[5,4]=-2
S[5,7]=2

b = np.zeros(6)
c = np.zeros(8)
c[3]=1 # E4 rxn que produce F420; maximizando produccion de energia
lb=np.zeros(8)
lb[0]=10 # Sustrato limitante igual a CO2
ub=np.array([1000]*8)

res = linprog(-c, A_eq=S, b_eq=b, bounds=(zip(lb, ub)) )
print 'Optimal value:', res.fun, '\nX:', res.x

Optimal value: -1000.0 
X: [   10.   520.    10.  1000.   500.    10.   510.   500.]


In [59]:
S = np.zeros((6,9))
S

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [65]:
b = np.zeros((6,1))
c = np.zeros((9,1))
c[3]=1 # E4 rxn que produce F420; maximizando produccion de energia
print "b"
print b
print 'c'
print c

b
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
c
[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [67]:
lb=np.zeros(9)
lb[0]=10 # Sustrato limitante igual a CO2
ub=np.array([1000]*9)

In [68]:
print lb

[ 10.   0.   0.   0.   0.   0.   0.   0.   0.]


In [69]:
print ub

[1000 1000 1000 1000 1000 1000 1000 1000 1000]


In [70]:
zip(lb, ub)

[(10.0, 1000),
 (0.0, 1000),
 (0.0, 1000),
 (0.0, 1000),
 (0.0, 1000),
 (0.0, 1000),
 (0.0, 1000),
 (0.0, 1000),
 (0.0, 1000)]